# Project information
site_name: "Kenrick's QRH"
site_description: 'A personal quick reference handbook'
site_author: 'Kenrick Turner'
site_url: 'https://qrh.kenners.org/'
apple_web_app_title: 'QRH'

# Repository
repo_name: 'kenners/qrh'
repo_url: 'https://github.com/kenners/qrh'

# Copyright
copyright: 'Copyright &copy; 2019 Kenrick Turner'

# Theme
theme:
  name: null
  custom_dir: 'theme/mkdocs-material/material'
  language: 'en'
  palette:
    primary: 'teal'
    accent: 'teal'
  font:
    text: 'B612'
    code: 'B612 Mono'
  logo: 'assets/img/icons/icon.svg'
  favicon: 'favicon.ico'
  appletouch:
    120: 'assets/img/icons/120.png'
    180: 'assets/img/icons/180.png'
    152: 'assets/img/icons/152.png'
    167: 'assets/img/icons/167.png'
  # 404 page
  static_templates:
    - 404.html
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  feature: null


extra:
  search:
    language: 'en'
    tokenizer: '[\s\-\.]+'
  manifest: 'manifest.json'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - meta

# Page tree
#nav:
#  - Home: index.md
#  - Obstetrics: obs.md
#  - Conditions:
#    - Angioedema: conditions/angioedema.md