# Project information
site_name: "Kenrick's QRH"
site_description: 'A personal quick reference handbook'
site_author: 'Kenrick Turner'
site_url: 'https://qrh.kenners.org/'

# Repository
repo_name: 'kenners/qrh'
repo_url: 'https://github.com/kenners/qrh'

# Copyright
copyright: 'Copyright &copy; 2019 Kenrick Turner'

# Theme
theme:
  name: null
  custom_dir: 'theme/mkdocs-material/material'
  language: 'en'
  palette:
    primary: 'teal'
    accent: 'teal'
  font:
    text: 'B612'
    code: 'B612 Mono'
  logo:
    icon: 'done_outline'
  favicon:
  # 404 page
  static_templates:
    - 404.html
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  feature: null


extra:
  search:
    language: 'en'
    tokenizer: '[\s\-\.]+'
  #manifest: 'manifest.webmanifest'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - meta

# Page tree
#nav:
#  - Home: index.md
#  - Obstetrics: obs.md
#  - Conditions:
#    - Angioedema: conditions/angioedema.md