# Project information
site_name: 'Kenners QRH'
site_description: 'A personal quick reference handbook'
site_author: 'Kenrick Turner'
site_url: 'https://fyi.kenners.org/'

# Repository
repo_name: 'kenners/fyi.kenners.org'
repo_url: 'https://github.com/kenners/fyi.kenners.org'

# Copyright
copyright: 'Copyright &copy; 2019 Kenrick Turner'

# Theme
theme:
  name: null
  custom_dir: 'theme/mkdocs-material/material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'B612'
    code: 'B612 Mono'
  logo:
    icon: 'book'
  feature: null


extra:
  search:
    language: 'en'
    tokenizer: '[\s\-\.]+'
  #manifest: 'manifest.webmanifest'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - meta

# Page tree
#nav:
#  - Home: index.md
#  - Obstetrics: obs.md
#  - Conditions:
#    - Angioedema: conditions/angioedema.md